import { DocumentationRule, ProgressNote } from "@/types/doctor/ipd/progress-note-types";


export const PROGRESS_NOTES: Record<string, ProgressNote[]> = {
  UHID12345685: [
    {
      id: "PN-1001",
      uhid: "UHID12345685",
      title: "Morning Ward Round",
      author: "Dr. Amit Verma",
      role: "Doctor",
      category: "Doctor Round",
      priority: "Routine",
      createdAt: "Today · 08:40 AM",
      status: "Signed & Locked",
      subjective: "Patient comfortable at rest. No recurrent chest pain since last evening.",
      objective: "Hemodynamically stable. BP 120/80 mmHg, pulse 78/min, SpO₂ 98%.",
      assessment: "Stable angina with controlled symptoms. No signs of acute cardiac event.",
      plan: "Continue ACS protocol. Continue antiplatelet and statin therapy. Await serial cardiology review.",
      noteText: "Patient comfortable at rest. No recurrent chest pain since last evening. Hemodynamically stable. Continue ACS protocol. Await serial cardiology decision.",
      vitals: { bp: "120/80", pulse: "78", temp: "98.4", spo2: "98", pain: "0" },
    },
    {
      id: "PN-1002",
      uhid: "UHID12345685",
      title: "Cardiology Review",
      author: "Dr. Amit Verma",
      role: "Doctor",
      category: "Clinical Review",
      priority: "Important",
      createdAt: "Yesterday · 06:30 PM",
      status: "Signed & Locked",
      subjective: "Intermittent exertional discomfort reported earlier, now improved.",
      objective: "ECG without dynamic ST elevation. Troponin-I within normal limits.",
      assessment: "Stable angina without evidence of acute myocardial injury.",
      plan: "Continue antiplatelet and anticoagulation. Reassess after biomarkers and echocardiography.",
      noteText: "ECG without dynamic ST elevation. Continue antiplatelet and anticoagulation. Reassess after biomarkers and echocardiography.",
      vitals: { bp: "124/82", pulse: "80", temp: "98.6", spo2: "97", pain: "1" },
    },
    {
      id: "PN-1003",
      uhid: "UHID12345685",
      title: "Nursing Handover",
      author: "Nurse Kavita",
      role: "Nurse",
      category: "Nursing Update",
      priority: "Routine",
      createdAt: "Yesterday · 08:00 PM",
      status: "Signed & Locked",
      subjective: "Patient denies chest pain and shortness of breath.",
      objective: "Patient alert and oriented. Pain score 1/10. Oral intake adequate.",
      assessment: "Comfortable and stable during evening shift.",
      plan: "Continue routine monitoring. Escalate if chest pain or breathing difficulty develops.",
      noteText: "Patient alert and oriented. No acute distress. Continue routine monitoring and medication schedule.",
      vitals: { bp: "124/82", pulse: "80", temp: "98.6", spo2: "97", pain: "1" },
    },
  ],
  UHID12345684: [
    {
      id: "PN-2001",
      uhid: "UHID12345684",
      title: "Morning Ward Round",
      author: "Dr. Priya Nair",
      role: "Doctor",
      category: "Doctor Round",
      priority: "Important",
      createdAt: "Today · 09:30 AM",
      status: "Signed & Locked",
      subjective: "Fever persists intermittently. Oral intake reduced.",
      objective: "Temperature 99.1°F, mild tachycardia, SpO₂ 97% on room air.",
      assessment: "Viral fever under observation. Awaiting malaria antigen report.",
      plan: "Continue antipyretic therapy, maintain hydration, review pending investigation.",
      noteText: "Fever persists intermittently. Continue antipyretics and hydration. Await malaria report.",
      vitals: { bp: "110/70", pulse: "84", temp: "99.1", spo2: "97", pain: "2" },
    },
  ],
  UHID12345683: [
    {
      id: "PN-3001",
      uhid: "UHID12345683",
      title: "ICU Critical Care Round",
      author: "Dr. Rahul Mehta",
      role: "Doctor",
      category: "Doctor Round",
      priority: "Urgent",
      createdAt: "Today · 08:30 AM",
      status: "Signed & Locked",
      subjective: "Patient remains drowsy and unable to provide reliable history.",
      objective: "BP 90/60, pulse 110/min, SpO₂ 92% on supplemental oxygen. Lactate elevated.",
      assessment: "Post-operative sepsis with ongoing hemodynamic instability.",
      plan: "Continue vasopressor support, administer scheduled antibiotic, repeat lactate and cultures.",
      noteText: "Patient remains critical. Lactate rising. Escalate antibiotic coverage and continue vasopressor support.",
      vitals: { bp: "90/60", pulse: "110", temp: "100.8", spo2: "92", pain: "6" },
    },
  ],
};

export const DOCUMENTATION_RULES: DocumentationRule[] = [
  { id: "R1", label: "Author role and identity recorded", completed: true },
  { id: "R2", label: "Date and time of documentation recorded", completed: true },
  { id: "R3", label: "Clinical assessment documented", completed: true },
  { id: "R4", label: "Plan and next action documented", completed: true },
  { id: "R5", label: "Relevant vitals reviewed or documented", completed: false, detail: "Recommended for each ward-round note" },
  { id: "R6", label: "Pending investigations acknowledged", completed: false, detail: "Review pending laboratory or imaging reports" },
];

export function getProgressNotes(uhid: string): ProgressNote[] {
  return PROGRESS_NOTES[uhid] ?? PROGRESS_NOTES.UHID12345685;
}