// lib/admission-desk/icu/icu-data.ts
import type { IcuPatient } from "@/types/admission-desk/icu/icu-types";

export const ICU_FLOORS = ["Ground Floor", "First Floor", "Second Floor"];
export const ICU_WARDS = ["ICU-A", "ICU-B", "ICU-C"];
export const ICU_DOCTORS = ["Dr. Amit Verma", "Dr. Rahul Mehta", "Dr. Priya Nair", "Dr. Sanjana Ghosh"];
export const ICU_RMOS = ["Dr. Kabir Sen (RMO)", "Dr. Ayesha Khan (RMO)", "Dr. Vivek Rao (RMO)"];
export const ICU_NURSES = ["Nurse Kavita", "Nurse Priya", "Nurse Anjali", "Nurse Neha", "Nurse Ravi", "Nurse Pooja"];

export const ICU_PATIENTS: IcuPatient[] = [
  {
    icuId: "ICU-2026-001",
    uhid: "UHID12345685",
    patientName: "Ravi Sharma",
    dateOfBirth: "1978-04-12",
    age: 48,
    gender: "Male",
    mobileNumber: "+91 98765 43210",
    alternativeMobile: "+91 98765 43211",
    emergencyContactNumber: "+91 98765 00011",
    emergencyContactName: "Sunita Sharma",
    emergencyContactRelationship: "Wife",
    address: "12, MG Colony, Sector 14",
    city: "New Delhi",
    state: "Delhi",
    pinCode: "110001",
    aadharNumber: "XXXX-XXXX-4521",
    ayushmanCardNumber: "PMJAY-77229981",
    floor: "First Floor",
    ward: "ICU-A",
    room: "Room-1",
    bed: "ICU-A-01",
    currentCondition: "Post-PCI monitoring, hemodynamically stable",
    status: "Stable",
    admissionType: "Emergency",
    referredFrom: "ER-20260827-001",
    assignedDoctor: "Dr. Amit Verma",
    assignedRmo: "Dr. Kabir Sen (RMO)",
    assignedNurses: [
      { date: "2026-08-27", shift: "Morning", nurseName: "Nurse Kavita" },
      { date: "2026-08-27", shift: "Evening", nurseName: "Nurse Anjali" },
      { date: "2026-08-27", shift: "Night", nurseName: "Nurse Neha" },
    ],
    admissionDate: "2026-08-27",
    admissionTime: "09:30 AM",
    admittedBy: "Dr. Amit Verma",
    allergies: ["Penicillin"],
    diagnosis: "Acute Myocardial Infarction - Post PCI",
    notes: "Patient responding well to treatment. Monitor vitals every 2 hours.",
  },
  {
    icuId: "ICU-2026-002",
    uhid: "UHID12398211",
    patientName: "Unknown Male (RTA)",
    dateOfBirth: undefined,
    age: 30,
    gender: "Male",
    mobileNumber: "",
    alternativeMobile: "",
    emergencyContactNumber: "",
    emergencyContactName: "",
    emergencyContactRelationship: "",
    address: "",
    city: "",
    state: "",
    pinCode: "",
    aadharNumber: "",
    ayushmanCardNumber: "",
    floor: "Second Floor",
    ward: "ICU-B",
    room: "Room-3",
    bed: "ICU-B-03",
    currentCondition: "Post-op laparotomy, on ventilator support, sedated",
    status: "Critical",
    admissionType: "OT",
    referredFrom: "OT-20260827-005",
    assignedDoctor: "Dr. Rahul Mehta",
    assignedRmo: "Dr. Vivek Rao (RMO)",
    assignedNurses: [
      { date: "2026-08-27", shift: "Morning", nurseName: "Nurse Anjali" },
      { date: "2026-08-27", shift: "Evening", nurseName: "Nurse Ravi" },
      { date: "2026-08-27", shift: "Night", nurseName: "Nurse Kavita" },
    ],
    admissionDate: "2026-08-27",
    admissionTime: "11:15 AM",
    admittedBy: "Dr. Rahul Mehta",
    allergies: [],
    diagnosis: "Multiple Traumatic Injuries - Post Splenectomy",
    notes: "Critical care required. Ventilator settings: AC/VC, TV 450ml, RR 16, FiO2 40%.",
  },
  {
    icuId: "ICU-2026-003",
    uhid: "UHID12345750",
    patientName: "Meera Joshi",
    dateOfBirth: "1995-11-02",
    age: 30,
    gender: "Female",
    mobileNumber: "+91 90011 22334",
    alternativeMobile: "+91 90011 99887",
    emergencyContactNumber: "+91 90011 99887",
    emergencyContactName: "Ramesh Joshi",
    emergencyContactRelationship: "Father",
    address: "45, Green Park Extension",
    city: "New Delhi",
    state: "Delhi",
    pinCode: "110016",
    aadharNumber: "XXXX-XXXX-8821",
    ayushmanCardNumber: "",
    tpaName: "Star Health Insurance",
    healthInsuranceName: "Star Comprehensive",
    insurancePolicyNumber: "SH-88221134",
    floor: "First Floor",
    ward: "ICU-A",
    room: "Room-2",
    bed: "ICU-A-02",
    currentCondition: "Post-gastric lavage, stable, under psychiatric observation",
    status: "Under Observation",
    admissionType: "Emergency",
    referredFrom: "ER-20260827-003",
    assignedDoctor: "Dr. Priya Nair",
    assignedRmo: "Dr. Ayesha Khan (RMO)",
    assignedNurses: [
      { date: "2026-08-27", shift: "Morning", nurseName: "Nurse Neha" },
      { date: "2026-08-27", shift: "Evening", nurseName: "Nurse Priya" },
      { date: "2026-08-27", shift: "Night", nurseName: "Nurse Anjali" },
    ],
    admissionDate: "2026-08-27",
    admissionTime: "10:45 AM",
    admittedBy: "Dr. Priya Nair",
    allergies: [],
    diagnosis: "Drug Overdose - Suicide Attempt",
    notes: "Psychiatry consult done. Suicide risk assessment pending. Keep under constant observation.",
  },
  {
    icuId: "ICU-2026-004",
    uhid: "UHID12345801",
    patientName: "Suresh Yadav",
    dateOfBirth: "1968-03-15",
    age: 58,
    gender: "Male",
    mobileNumber: "+91 98112 33445",
    alternativeMobile: "",
    emergencyContactNumber: "+91 98112 55667",
    emergencyContactName: "Ramesh Yadav",
    emergencyContactRelationship: "Brother",
    address: "78, Lajpat Nagar",
    city: "New Delhi",
    state: "Delhi",
    pinCode: "110024",
    aadharNumber: "XXXX-XXXX-9921",
    ayushmanCardNumber: "PMJAY-88334455",
    floor: "Second Floor",
    ward: "ICU-C",
    room: "Room-1",
    bed: "ICU-C-01",
    currentCondition: "Post-op knee replacement, pain controlled, mobilizing with support",
    status: "Stable",
    admissionType: "IPD",
    referredFrom: "IPD-2026-00416",
    assignedDoctor: "Dr. Sanjana Ghosh",
    assignedRmo: "Dr. Kabir Sen (RMO)",
    assignedNurses: [
      { date: "2026-08-27", shift: "Morning", nurseName: "Nurse Ravi" },
      { date: "2026-08-27", shift: "Evening", nurseName: "Nurse Kavita" },
      { date: "2026-08-27", shift: "Night", nurseName: "Nurse Neha" },
    ],
    admissionDate: "2026-08-26",
    admissionTime: "04:30 PM",
    admittedBy: "Dr. Sanjana Ghosh",
    allergies: ["Sulfa Drugs"],
    diagnosis: "Post-operative Care - Total Knee Replacement",
    notes: "Physiotherapy started. DVT prophylaxis ongoing.",
  },
];

export function getIcuPatients() {
  return ICU_PATIENTS;
}

export const ICU_STATUS_OPTIONS: IcuPatient["status"][] = [
  "Stable", "Under Observation", "Critical", "Released", "Follow-up OPD", "Shifted to IPD",
];

export const ADMISSION_TYPE_OPTIONS: IcuPatient["admissionType"][] = ["Emergency", "IPD", "OT"];